---

- name: install yum updates
  yum: update_cache=yes


- name: install yum-utils 
  yum:
    name: yum-utils
    state: latest

- name: install container-selinux
  yum:
    name: http://mirror.centos.org/centos/7/extras/x86_64/Packages/container-selinux-2.107-3.el7.noarch.rpm
    state: latest

- name: Add repository for docker-ce
  command: "yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo"

- name: install docker svc 
  yum:
    name: docker-ce
    state: latest

- name: Start docker service docker, if not started
  service:
    name: docker
    state: started

- name: Install build tools
  yum:
    name: "@Development tools"
    state: present

    
- name: Install python tools
  yum:
    name: "python-devel"
    state: present

- name: upgrade pip
  command: "pip install --upgrade pip"

    
- name: Install docker-compose
  pip:
    name: ['zipp','docker-compose']
    extra_args: --ignore-installed